### ISSUE TITLE
Make the BuildFactory fetch the script from resources rather than from const data

### ISSUE THREAD

**Issue by waddlesplash** [HaikuArchives/Yab#11]
This will fix the problem that the BuildFactory does not currently work due to flex changes.

**Comment by waddlesplash** [comment]
Fixed in a different way in e026c2cae2e6a4f005b77a82ad71a4d115a1e4bc.

**Comment by bbjimmy** [comment]
still doesn't work, building yab_IDE .... 

main.o: In function `parse_arguments':
main.c:(.text+0xcbc): undefined reference to`yydebug'
collect2: ld returned 1 exit status
make: **\* [yab] Error 1
